image: node:6

pages:
  stage: deploy
  script:
    - apt-get -qq update && apt-get -qq -y install bzip2 gifsicle
    - npm install -g grunt-cli bower
    - npm install
    - bower install --allow-root 
    - grunt build
    - mkdir public
    - cp -a dist/* public/
  artifacts:
    paths:
    - public
  only:
  - master
